### ISSUE TITLE
how to maximize firefox using BrowserstackFeatureContext 

### ISSUE THREAD

**Issue by ghost** [nulpunkt/behat-mink-browserstack#1]
I tried 
class FeatureContext extends MinkContext
{
   private static $driver = null;
    public function __construct($params)
    {
        $this->setBrowserstackParams($params);
        $host = "http://{$this->browserstack_username}:{$this->browserstack_password}@hub.browserstack.com/wd/hub";
        if (self::$driver === null) {
            self::$driver = new Selenium2Driver('', $this->capabilities, $host);
        }
        $mink = new Mink(array(
            'selenium2' => new Session(self::$driver),
        ));
        $mink->setDefaultSessionName('selenium2');
        $this->setMink($mink);
        $this->setMinkParameters($params);
        $mink->getSession('selenium2')->getDriver()->maximizeWindow(null);

but id did not worked out.

**Comment by nulpunkt** [comment]
Hi,

I'm not sure this is the place to ask. I don't know why it does not work for you. I'd suggest that you ask via the official channels for the php selenium code. Best of luck :)
